#! /bin/sh

# AtLauncher graphical error
export _JAVA_AWT_WM_NONREPARENTING=1

bspc rule -a firefox desktop='^3' follow=on
bspc rule -a discord desktop='^4' follow=on
bspc rule -a com-atlauncher-App desktop='^5' state=floating follow=on
bspc rule -a Xarchiver state=floating
bspc rule -a Ocrdesktop state=floating
bspc rule -a Zathura state=tiling
bspc rule -a Galculator state=floating
bspc rule -a org.pwmt.zathura state=tiling
bspc rule -a floating_window state=floating
bspc rule -a Toolkit state=floating

bspc monitor -d I II III IV V
# bspc desktop III -l monocle

sxhkd &                          # Keybindings
# hsetroot -solid "#34324a"        # Bg Color
~/.fehbg &                       # Bg image
lxsession &                      # Session manager
polybar &                        # Status Bar
picom &                          # Compositor
pidof redshift || redshift-gtk & # Night Light
nm-applet &                      # WLAN icon
volumeicon &                     # Volume icon
thunar --daemon &                # File manager daemon
clipmenud &                      # Clipboard history
# discord &                        # Discord

bspc config border_width         2
bspc config window_gap          12

# Colors
bspc config normal_border_color  '#2b2a3e'
bspc config focused_border_color '#c792ea'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
